Adding label to kube-system namespace
run-x/opta pull request #728
Opened 2022-02-22 22:45 UTC by bigbitbus

# Description
Add a label to kube-system because of this:
https://linkerd.io/2.10/features/ha/#proxy-injector-failure-policy

# Safety checklist
* [X ] This change is backwards compatible and safe to apply by existing users
* [X ] This change will NOT lead to data loss
* [X ] This change will NOT lead to downtime who already has an env/service setup

## How has this change been tested, beside unit tests?
Circle Testing tbd

2022-02-22 23:32 UTC, RemyDeWolf reviewed
After reading the linkerd doc, my understanding is that it would only add the proxy if 
`linkerd.io/inject: enabled` is set. But we don't set this to the kube-system namespace right?

Also, the issue with this change is that it won't work with terraform generator, because terraform would not add the label. Would that be a blocker?
-> We can have the label done by helm, here is an example https://gist.github.com/kvudata/12ba57ae1e7f01799aaa7f36350a9b2e

2022-02-23 14:28 UTC, bigbitbus commented
> After reading the linkerd doc, my understanding is that it would only add the proxy if `linkerd.io/inject: enabled` is set. But we don't set this to the kube-system namespace right?
> 
> Also, the issue with this change is that it won't work with terraform generator, because terraform would not add the label. Would that be a blocker? -> We can have the label done by helm, here is an example https://gist.github.com/kvudata/12ba57ae1e7f01799aaa7f36350a9b2e

This label requirement came from a customer incident @rabbitfang addressed and then created the ticket (see description here: https://run-x.atlassian.net/browse/RUNX-1160); he suggests we add the label config.linkerd.io/admission-webhooks=disabled on the kube-system namespace and that seemed to have fixed the issue of the webhook.

True, the terraform will not contain this because we are directly invoking the API instead of using Terraform; I feel running a helm chart via terraform to just set one label is going to be much slower than invoking this API call, for every user/cluster. We haven't solved the question of what to do with all this Python glue code (within processors) in Terraform code generation; once we have a solution to that it should wrap up this issue. 

Also, the approach in the github gist will require helm to "adopt" or "import" the kube-system namespace (As helm does not work out-of-the-box with pre-existing resources); I am a little uncomfortable touching the kube-system namespace that is essentially managed by AKS/EKS/GKE any more than needed.

Lets chat more if you want.

2022-02-24 19:04 UTC, rabbitfang requested changes

2022-02-24 19:04 UTC, rabbitfang commented on modules/aws_k8s_base/aws_k8s_base.py
>          list_namespaces()
```suggestion
        list_namespaces()
        add_linkerd_label_to_kubesystem()
```

We are using `list_namespaces` to verify connectivity to the cluster, so we shouldn't try adding the label to the namespace until we are sure we can connect. Ditto for later instances.

2022-02-24 21:41 UTC, bigbitbus commented
closing for #732 instead.

2022-02-24 21:41 UTC, closed without merging